name: CMake Build

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-24.04, macos-latest ]
        build_type: [ Debug ] #[ Debug, Release ]
        c_compiler: [ clang ]
        include:
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++-18

          - os: ubuntu-24.04
            c_compiler: clang
            cpp_compiler: clang++-18

        # Don't include the following configurations in the matrix
#        exclude:
#          - os: macos-latest
#            build_type: Debug
#
#          - os: ubuntu-24.04
#            build_type: Release

    steps:
      - name: Install Dependencies
        if: matrix.os == 'macos-latest'
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=TRUE
          brew update
          brew install gcc readline ninja cmake git
          brew reinstall llvm
          echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.bash_profile
          echo 'export PATH="/opt/homebrew/opt/gcc/bin:$PATH"' >> ~/.bash_profile
          echo 'export PATH="/opt/homebrew/opt/gcc/lib/gcc/14:$PATH"' >> ~/.bash_profile   
          . ~/.bash_profile

      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      # Build the project
      - name: Build PrivacyShield
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo ./scripts/build.sh

      - name: Install Blake3
        if: matrix.os == 'macos-latest'
        run: |
          sudo ./scripts/install-blake3.sh ${{ matrix.c_compiler }}

      - name: Configure CMake
        if: matrix.os == 'macos-latest'
        run: >          
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++
          -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang
          -DCMAKE_CXX_FLAGS="-stdlib++-isystem /opt/homebrew/Cellar/gcc/14.1.0_1/include/c++/14 -cxx-isystem /opt/homebrew/Cellar/gcc/14.1.0_1/include/c++/14/aarch64-apple-darwin23"
          -DCMAKE_EXE_LINKER_FLAGS="-L /opt/homebrew/Cellar/gcc/14.1.0_1/lib/gcc/14 -Wl,-rpath,/opt/homebrew/opt/gcc/lib/gcc/current"
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }} -G Ninja
          # -DCMAKE_CXX_FLAGS="-stdlib=libstdc++ -stdlib++-isystem /opt/homebrew/Cellar/gcc/14.1.0_1/include/c++/14 -cxx-isystem /opt/homebrew/Cellar/gcc/14.1.0_1/include/c++/14/aarch64-apple-darwin23 -L /opt/homebrew/Cellar/gcc/14.1.0_1/lib/gcc/14 -Wl,-rpath,/opt/homebrew/opt/gcc/lib/gcc/current"

      - name: Build
        if: matrix.os == 'macos-latest'
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j 4

      # Run Tests
      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest -j 4
