name: CMake Build

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, macos-latest ]
        build_type: [ Debug ]
        c_compiler: [ clang, gcc ]
        include:
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++-19

          - os: macos-latest
            c_compiler: gcc
            cpp_compiler: g++-14

          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++-19

          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++-14

    steps:
      - name: Install Dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
               if [[ "${{ matrix.c_compiler }}" == "gcc" ]]; then
                  sudo apt-get install cmake ninja-build gcc-14 g++-14 libsodium-dev libsodium23 libgcrypt20-dev -y
               elif [[ "${{ matrix.c_compiler }}" == "clang" ]]; then
                  wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
                  sudo apt-add-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main"
                  sudo apt-get update
                  sudo apt-get install cmake ninja-build clang-19 clang-tools-19 libsodium-dev libsodium23 libgcrypt20-dev -y
               fi
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
              if [[ "${{ matrix.c_compiler }}" == "clang" ]]; then
                  brew install cmake ninja libsodium libgcrypt llvm@19 lld
              else
                  brew install cmake ninja libsodium libgcrypt
              fi
          fi

      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          # Set the paths to the GCC include and lib directories on macOS
          if [[ "${{ matrix.os }}" == "macos-latest" && "${{ matrix.c_compiler }}" == "clang" ]]; then
            echo "clangpath=$(brew --prefix llvm@19)/bin/clang" >> "$GITHUB_OUTPUT"
            echo "clangxxpath=$(brew --prefix llvm@19)/bin/clang++" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.c_compiler }}" == "clang" ]]; then
            echo "clangpath=clang-19" >> "$GITHUB_OUTPUT"
            echo "clangxxpath=clang++-19" >> "$GITHUB_OUTPUT"
          fi
          if [[ "${{ matrix.c_compiler }}" == "gcc" ]]; then
            echo "gccpath=gcc-14" >> "$GITHUB_OUTPUT"
            echo "gxxpath=g++-14" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure CMake
        run: |
          if [[ "${{ matrix.c_compiler }}" == "gcc" ]]; then
            cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_CXX_COMPILER=${{ steps.strings.outputs.gxxpath }} \
              -DCMAKE_C_COMPILER=${{ steps.strings.outputs.gccpath }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -S ${{ github.workspace }} -G Ninja
          elif [[ "${{ matrix.c_compiler }}" == "clang" && "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_CXX_COMPILER=${{ steps.strings.outputs.clangxxpath }} \
              -DCMAKE_C_COMPILER=${{ steps.strings.outputs.clangpath }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -S ${{ github.workspace }} -G Ninja
          elif [[ "${{ matrix.c_compiler }}" == "clang" && "${{ matrix.os }}" == "macos-latest" ]]; then
            cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_CXX_COMPILER=${{ steps.strings.outputs.clangxxpath }} \
              -DCMAKE_C_COMPILER=${{ steps.strings.outputs.clangpath }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_EXE_LINKER_FLAGS="-L$(brew --prefix llvm@19)/lib/c++ -Wl,-rpath,$(brew --prefix llvm@19)/lib/c++" \
              -S ${{ github.workspace }} -G Ninja
          fi

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j 4

      # Run Tests
      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --output-on-failure -j 4
